### ISSUE TITLE
structure

### ISSUE THREAD

**Issue by SoluMilken** [Yoctol/strpipe#2]
## node
- request (check dependencies)
- output
- build
- forward operation
- backward operation
- save
- load

**Comment by SoluMilken** [comment]
## manager
- init 
- add
- build
- forward
- backward
- load (classmethod)
- save

**Comment by SoluMilken** [comment]
```python
class ComputeMaxLength(Node):
    def __init__(self, input_path, sentences):
        blabla

    def build(self):
         self.maxlen = ~~~~

    def output(self):
         return self.maxlen

    def forward(self):
          if self.maxlen is None:
               raise Error

    def backward(self):
          if self.maxlen is None:
               raise Error
  
    @classmethod
    def load(self, baba):
         self.maxlen = baba['ComputeMaxLength']['maxlen']
```

**Comment by stegben** [comment]
`node` should be renamed to `Step` or sth else since we're not building DAG,

**Comment by SoluMilken** [comment]
## node builder
- request
- build
- export

## node forward op
- request
- forward
- export
- output

## node backward op
- request
- backward
- export
- output

## node
node = node builder + node forward op + node backward op

**Comment by SoluMilken** [comment]
很有可能真的是dag
因為
token2index(maxlen(從compute max len來), word2index（從 build vocab 來）)
