### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by SoluMilken** [Yoctol/strpipe#3]
https://hackmd.io/nIS-uzdBT2Go95MT2ISNBA

**Comment by SoluMilken** [comment]
覺得寫得很好的巴巴
https://stuff.mit.edu/afs/sipb/project/sage/packages/cython-0.9.6.8.b/Doc/sharing.html

**Comment by SoluMilken** [comment]
https://stackoverflow.com/questions/1070497/c-convert-hex-string-to-signed-integer

**Comment by stegben** [comment]
References should move to Wiki
